services:
  fastapi:
    container_name: fastapiTeste
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src  # Mapeia a pasta src/ local para /src no container
    environment:
      - PYTHONPATH=/src
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]